version: '3.8'

services:
  telegram-client:
    build:
      context: ..
      dockerfile: telegram-client/Dockerfile
    container_name: telegram-client
    restart: unless-stopped
    environment:
      - GRPC_HOST=192.168.1.12:50051
    volumes:
      - ../vault.json:/app/vault.json:ro

