version: '3.8'

services:
  telegram-client:
    build:
      context: ..
      dockerfile: telegram-client/Dockerfile
    container_name: telegram-client
    restart: unless-stopped
    network_mode: host
    environment:
      - GRPC_HOST=127.0.0.1:50051
    volumes:
      - ../vault.json:/app/vault.json:ro

